### ISSUE TITLE
Importation de masse : la recherche d'un parent qui n'existe pas fait planter l'appli

### ISSUE THREAD

**Issue by equinton** [collec-science/collec-science#786]
PHP Fatal error:  Uncaught TypeError: Sample::getIdFromIdentifier(): Argument #2 ($collection_id) must be of type int, null given, called in /var/www/html/collec-science/collec-science-git/modules/classes/importObject.class.php on line 654 and defined in /var/www/html/collec-science/collec-science-git/modules/classes/sample.class.php:205\nStack trace:\n#0 /var/www/html/collec-science/collec-science-git/modules/classes/importObject.class.php(654): Sample->getIdFromIdentifier()\n#1 /var/www/html/collec-science/collec-science-git/modules/classes/importObject.class.php(747): ImportObject->prepareLine()\n#2 /var/www/html/collec-science/collec-science-git/modules/gestion/import.php(80): ImportObject->controlAll()\n#3 /var/www/html/collec-science/collec-science-git/framework/controller.php(627): include('...')\n#4 /var/www/html/collec-science/collec-science-git/index.php(3): include('...')\n#5 {main}\n  thrown in /var/www/html/collec-science/collec-science-git/modules/classes/sample.class.php on line 205, referer: https://collec.osupytheas.fr/index.php?module=importChange

**Comment by equinton** [comment]
Problème lié à une longueur de ligne d'entête qui dépasse 1000 caractères. Le code a été corrigé pour ne plus limiter la taille de la ligne dans fgetcsv.
